# Generated by Django 5.0.2 on 2024-04-19 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="oder_number",
            new_name="order_number",
        ),
    ]
