# Generated by Django 5.0.2 on 2024-04-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_rename_amount_paid_payment_ref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
