# Generated by Django 5.0.2 on 2024-03-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("price", models.FloatField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(default="No description available")),
                ("stock", models.IntegerField(default=0)),
                ("image", models.ImageField(upload_to="product_pic")),
            ],
        ),
    ]
